### ISSUE TITLE
Invalid Letsencrypt renewal file

### ISSUE THREAD

**Issue by jernst** [uboslinux/ubos-admin#679]
```
# certbot renew --quiet --agree-tos 

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/certbot/renewal.py", line 67, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/usr/lib/python3.7/site-packages/certbot/storage.py", line 444, in __init__
    "file reference".format(self.configfile))
certbot.errors.CertStorageError: renewal config file {'renewalparams': {'account': '4d150246b484c7a4e66433204966e65f', 'authenticator': 'webroot', 'server': 'https://acme-v02.api.letsencrypt.org/directory', 'post_hook': '/usr/bin/systemctl restart httpd.service', 'webroot_map': {'example.com': '/ubos/http/wellknown/s71dd9411f9fda663a289e33c4f9e56873421dbf1'}}} is missing a required file reference
Renewal configuration file /etc/letsencrypt/renewal/example.conf is broken. Skipping.
```

**Comment by jernst** [comment]
Here is a correct one, for example.com
```
# renew_before_expiry = 30 days
version = 0.32.0
archive_dir = /etc/letsencrypt/archive/example.com
cert = /etc/letsencrypt/live/example.com/cert.pem
privkey = /etc/letsencrypt/live/example.com/privkey.pem
chain = /etc/letsencrypt/live/example.com/chain.pem
fullchain = /etc/letsencrypt/live/example.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 6bf0fdc8237f055b6f18bdfd4e53781d
authenticator = webroot
webroot_path = /ubos/http/wellknown/s125c1ee3506e51652b1042e72835fe49f46e4ca0,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
example.com = /ubos/http/wellknown/s125c1ee3506e51652b1042e72835fe49f46e4ca0
```
